source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZATimer_Example', :exclusive => true do
  pod "DZATimer", :path => "../"
end

target 'DZATimer_Tests', :exclusive => true do
  pod "DZATimer", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
